# Generated by Django 5.0.7 on 2024-07-22 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('PushEvent', 'PushEvent'), ('ReleaseEvent', 'ReleaseEvent'), ('WatchEvent', 'WatchEvent')], max_length=256)),
                ('public', models.BooleanField()),
                ('repo_id', models.IntegerField()),
                ('actor_id', models.IntegerField()),
            ],
        ),
    ]
